//
//  CleanViewController.swift
//  SenlaApp
//
//  Created by Igor Penkin on 23.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanDisplayLogic: AnyObject
{
  func displaySomething(viewModel: Clean.Something.ViewModel)
}

class CleanViewController: UIViewController, CleanDisplayLogic
{
  var interactor: CleanBusinessLogic?
  var router: (NSObjectProtocol & CleanRoutingLogic & CleanDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CleanInteractor()
    let presenter = CleanPresenter()
    let router = CleanRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
    func routeToTheDream() {
        
    }
    
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Clean.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Clean.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
